// File generated by FlutterFire CLI (run: dart run flutterfire_cli:flutterfire configure).
// Until you run that command, this is a placeholder so the app compiles.
// Get your config from Firebase Console → Project settings → Your apps → Web app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: "AIzaSyDZP0pNyMBs-mI5IliD3zUdSSCVq-C5Aig",
      authDomain: "abdallahgaber-portofolio.firebaseapp.com",
      projectId: "abdallahgaber-portofolio",
      storageBucket: "abdallahgaber-portofolio.firebasestorage.app",
      messagingSenderId: "131735027038",
      appId: "1:131735027038:web:5b405cd0965a7ff63a63cf",
      measurementId: "G-3RJK8ZXMEZ",
    );
  }
}
